"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Item = { product_name: string; quantity: number; unit: string; line_total_inr: number };
type Order = { id: string; status: string; payment_status: string; total_inr: number; created_at: string; delivery_address: string; order_items: Item[]; delivery: { status: string; requested_for: string | null } | null; estimated_delivery_date: string | null };
const label = (value: string) => value.replace(/_/g, " ");
const date = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`));

export default function OrderDetails({ params }: { params: Promise<{ id: string }> }) {
  const [order, setOrder] = useState<Order | null>(null); const [error, setError] = useState("");
  useEffect(() => { params.then(async ({ id }) => { try { const response = await fetch(`/api/orders?id=${encodeURIComponent(id)}`); const body = await response.json() as { orders?: Order[]; error?: string }; if (!response.ok || !body.orders?.[0]) throw new Error(body.error ?? "Order not found."); setOrder(body.orders[0]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Order not found."); } }); }, [params]);
  if (error) return <main className="page-shell"><div className="app-container"><Link href="/orders" className="soft-button">Back to orders</Link><p role="alert" className="notice mt-6">{error}</p></div></main>;
  if (!order) return <main className="page-shell"><div className="app-container text-slate-600">Loading order…</div></main>;
  return <main className="page-shell"><div className="mx-auto w-full max-w-3xl px-5 py-8"><Link href="/orders" className="soft-button">Back to orders</Link><section className="surface mt-5 p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">ORDER {order.id.slice(0, 8).toUpperCase()}</p><h1 className="mt-2 text-3xl font-extrabold">Your order details</h1><p className="mt-2 text-sm text-slate-600">Placed {new Date(order.created_at).toLocaleString("en-IN")}</p></div><span className="status-badge">{label(order.status)}</span></div><div className="mt-6 grid gap-4 rounded-xl bg-[#f7faf5] p-4 text-sm sm:grid-cols-2"><div><p className="font-semibold text-leaf">{order.estimated_delivery_date ? `Estimated delivery: ${date(order.estimated_delivery_date)}` : "Awaiting logistics scheduling"}</p><p className="mt-1 text-slate-600">{order.delivery ? `Delivery status: ${label(order.delivery.status)}` : "Delivery request has not been scheduled"}</p></div><div><p className="font-semibold">Payment</p><p className="mt-1 text-slate-600">{order.payment_status === "simulated_paid" ? "Simulated payment confirmed" : order.payment_status === "simulated_pending" ? "Payment simulation pending" : label(order.payment_status)}</p></div></div><p className="mt-5 text-sm text-slate-600">Delivery address: {order.delivery_address}</p><div className="mt-6 divide-y divide-green-950/10 border-y border-green-950/10">{order.order_items.map((item) => <div key={`${item.product_name}-${item.unit}`} className="flex items-center justify-between gap-4 py-4 text-sm"><span><b>{item.product_name}</b><br />{item.quantity} {item.unit}</span><span>₹{Number(item.line_total_inr).toLocaleString("en-IN")}</span></div>)}</div><p className="mt-6 text-xl font-extrabold">Total: ₹{Number(order.total_inr).toLocaleString("en-IN")}</p></section></div></main>;
}
