import { NextResponse } from "next/server";
import { createSupabaseServerClient } from "../../../../lib/supabase/server";

const units=["kg","quintal","piece","dozen","crate"]; const statuses=["draft","active","paused","archived"];
async function actor(){const s=await createSupabaseServerClient();const {data:{user}}=await s.auth.getUser();if(!user)return [s,null] as const;const {data:p}=await s.from("profiles").select("role").eq("id",user.id).single();return [s,p&&["farmer","fpo"].includes(p.role)?user:null] as const}
export async function GET(){const[s,u]=await actor();if(!u)return NextResponse.json({error:"Forbidden"},{status:403});const {data,error}=await s.from("products").select("*,inventory(*)").eq("seller_id",u.id).order("created_at",{ascending:false});return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json(data)}
export async function POST(r:Request){const[s,u]=await actor();if(!u)return NextResponse.json({error:"Forbidden"},{status:403});const b=await r.json();if(typeof b.name!=="string"||b.name.trim().length<2||typeof b.category!=="string"||b.category.trim().length<2||!Number.isFinite(b.price_inr)||b.price_inr<=0||!Number.isFinite(b.quantity)||b.quantity<0||!units.includes(b.unit)||!statuses.includes(b.status))return NextResponse.json({error:"Invalid product details."},{status:400});const {data,error}=await s.from("products").insert({seller_id:u.id,name:b.name.trim(),category:b.category.trim(),description:typeof b.description==="string"?b.description.trim()||null:null,price_inr:b.price_inr,unit:b.unit,status:b.status}).select().single();if(error)return NextResponse.json({error:error.message},{status:400});const inv=await s.from("inventory").insert({product_id:data.id,available_quantity:b.quantity,reorder_level:0});if(inv.error)return NextResponse.json({error:"Product created but inventory failed."},{status:500});return NextResponse.json(data,{status:201})}
export async function PATCH(r:Request){const[s,u]=await actor();if(!u)return NextResponse.json({error:"Forbidden"},{status:403});const b=await r.json();if(typeof b.id!=="string"||typeof b.name!=="string"||b.name.trim().length<2||typeof b.category!=="string"||b.category.trim().length<2||!Number.isFinite(b.price_inr)||b.price_inr<=0||!Number.isFinite(b.quantity)||b.quantity<0||!units.includes(b.unit)||!statuses.includes(b.status))return NextResponse.json({error:"Invalid product details."},{status:400});const product=await s.from("products").update({name:b.name.trim(),category:b.category.trim(),description:typeof b.description==="string"?b.description.trim()||null:null,price_inr:b.price_inr,unit:b.unit,status:b.status}).eq("id",b.id).eq("seller_id",u.id).select().maybeSingle();if(product.error||!product.data)return NextResponse.json({error:"Product not found or access denied."},{status:403});const inv=await s.from("inventory").update({available_quantity:b.quantity}).eq("product_id",b.id);if(inv.error)return NextResponse.json({error:inv.error.message},{status:400});return NextResponse.json(product.data)}
export async function DELETE(r:Request){const[s,u]=await actor();if(!u)return NextResponse.json({error:"Forbidden"},{status:403});const {id}=await r.json();const {data,error}=await s.from("products").update({status:"archived"}).eq("id",id).eq("seller_id",u.id).select().maybeSingle();return error||!data?NextResponse.json({error:"Product not found or access denied."},{status:403}):NextResponse.json({ok:true})}
