"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { LogOut } from "lucide-react";
import { dashboardForRole, type AppRole, type RegistrationRole } from "../lib/auth";
import { createSupabaseBrowserClient } from "../lib/supabase/browser";

const input = "mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-leaf focus:ring-2 focus:ring-green-100";
const roles: { value: RegistrationRole; label: string }[] = [{ value: "consumer", label: "Consumer" }, { value: "farmer", label: "Farmer" }, { value: "fpo", label: "Farmer Producer Organisation" }, { value: "bulk_buyer", label: "Bulk buyer" }];

export function LoginForm() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const supabase = createSupabaseBrowserClient(); const { data, error: loginError } = await supabase.auth.signInWithPassword({ email: String(form.get("email")), password: String(form.get("password")) }); if (loginError || !data.user) { setError(loginError?.message ?? "Unable to sign in."); setLoading(false); return; } const { data: profile, error: profileError } = await supabase.from("profiles").select("role").eq("id", data.user.id).single(); if (profileError || !profile) { await supabase.auth.signOut(); setError("This account does not have an authorised FarmDirect profile."); setLoading(false); return; } router.replace(dashboardForRole(profile.role as AppRole)); router.refresh(); }
  return <form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm font-semibold">Email<input className={input} name="email" type="email" autoComplete="email" required /></label><label className="block text-sm font-semibold">Password<input className={input} name="password" type="password" autoComplete="current-password" required /></label>{error && <p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-leaf py-3 text-sm font-bold text-white disabled:opacity-60">{loading ? "Signing in…" : "Log in"}</button><p className="text-center text-sm text-slate-600">New to FarmDirect? <Link className="font-bold text-leaf" href="/register">Create an account</Link></p></form>;
}

export function RegisterForm() {
  const router = useRouter(); const [role, setRole] = useState<RegistrationRole>("consumer"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setLoading(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password"), fullName: form.get("fullName"), role, phone: form.get("phone"), city: form.get("city"), state: form.get("state"), farmName: form.get("farmName"), organizationName: form.get("organizationName") }) }); const result = await response.json() as { error?: string }; if (!response.ok) { setError(result.error ?? "Unable to create account."); setLoading(false); return; } const supabase = createSupabaseBrowserClient(); const { error: loginError } = await supabase.auth.signInWithPassword({ email: String(form.get("email")), password: String(form.get("password")) }); if (loginError) { router.push("/login"); return; } router.replace(dashboardForRole(role)); router.refresh(); }
  return <form onSubmit={submit} className="mt-7 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold sm:col-span-2">I am joining as<select value={role} onChange={(e) => setRole(e.target.value as RegistrationRole)} className={input}>{roles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="block text-sm font-semibold">Full name<input className={input} name="fullName" required minLength={2}/></label><label className="block text-sm font-semibold">Phone<input className={input} name="phone" inputMode="tel"/></label>{role === "farmer" && <label className="block text-sm font-semibold sm:col-span-2">Farm name<input className={input} name="farmName" required /></label>}{role === "fpo" && <label className="block text-sm font-semibold sm:col-span-2">Organisation name<input className={input} name="organizationName" required /></label>}<label className="block text-sm font-semibold">City<input className={input} name="city" required /></label><label className="block text-sm font-semibold">State<input className={input} name="state" defaultValue="Maharashtra" required /></label><label className="block text-sm font-semibold sm:col-span-2">Email<input className={input} name="email" type="email" autoComplete="email" required /></label><label className="block text-sm font-semibold sm:col-span-2">Password<input className={input} name="password" type="password" minLength={8} autoComplete="new-password" required /><span className="mt-1 block text-xs font-normal text-slate-500">At least 8 characters.</span></label>{error && <p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700 sm:col-span-2">{error}</p>}<button disabled={loading} className="rounded-xl bg-leaf py-3 text-sm font-bold text-white disabled:opacity-60 sm:col-span-2">{loading ? "Creating account…" : "Create secure account"}</button><p className="text-center text-sm text-slate-600 sm:col-span-2">Already have an account? <Link className="font-bold text-leaf" href="/login">Log in</Link></p></form>;
}

export function LogoutButton({ className = "" }: { className?: string }) { const router = useRouter(); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function logout() { setLoading(true); setError(""); try { const { error: signOutError } = await createSupabaseBrowserClient().auth.signOut(); if (signOutError) { setError("Unable to sign out. Please try again."); return; } router.replace("/login"); router.refresh(); } catch { setError("Unable to sign out. Please try again."); } finally { setLoading(false); } } return <div className="relative"><button onClick={logout} disabled={loading} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold transition disabled:cursor-not-allowed disabled:opacity-60 ${className}`} aria-label="Log out of FarmDirect AI"><LogOut size={15} />{loading ? "Signing out…" : "Log out"}</button>{error && <p role="alert" className="absolute right-0 top-full z-40 mt-2 w-52 rounded-lg bg-red-50 px-3 py-2 text-xs font-medium text-red-700 shadow-sm">{error}</p>}</div>; }
