"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { LogOut } from "lucide-react";
import { dashboardForRole, type AppRole, type RegistrationRole } from "../lib/auth";
import { normalizeIndianPhone } from "../lib/phone";
import { createSupabaseBrowserClient } from "../lib/supabase/browser";

const input = "mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-leaf focus:ring-2 focus:ring-green-100";
const roles: { value: RegistrationRole; label: string }[] = [{ value: "consumer", label: "Consumer" }, { value: "farmer", label: "Farmer" }, { value: "fpo", label: "Farmer Producer Organisation" }, { value: "bulk_buyer", label: "Bulk buyer" }];

export function LoginForm() {
  const router = useRouter(); const [mode, setMode] = useState<"email" | "phone">("email"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [phone, setPhone] = useState(""); const [code, setCode] = useState(""); const [pendingPhone, setPendingPhone] = useState<string | null>(null);
  async function redirectForUser(userId: string) { const supabase = createSupabaseBrowserClient(); const { data: profile, error: profileError } = await supabase.from("profiles").select("role").eq("id", userId).single(); if (profileError || !profile) { await supabase.auth.signOut(); setError("This account does not have an authorised FarmDirect profile."); setLoading(false); return; } router.replace(dashboardForRole(profile.role as AppRole)); router.refresh(); }
  async function submitPassword(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(""); const form = new FormData(e.currentTarget); const s = createSupabaseBrowserClient(); const { data, error: loginError } = await s.auth.signInWithPassword({ email: String(form.get("email")), password: String(form.get("password")) }); if (loginError || !data.user) { setError(loginError?.message ?? "Unable to sign in."); setLoading(false); return; } await redirectForUser(data.user.id); }
  async function sendOtp(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const normalized = normalizeIndianPhone(phone); if (!normalized) { setError("Enter a valid Indian mobile number, for example +919876543210."); return; } setLoading(true); setError(""); const { error: otpError } = await createSupabaseBrowserClient().auth.signInWithOtp({ phone: normalized, options: { shouldCreateUser: false } }); if (otpError) { setError("We could not find a verified FarmDirect account with that mobile number. Use email and password, or verify your mobile from your account first."); setLoading(false); return; } setPendingPhone(normalized); setCode(""); setLoading(false); }
  async function verifyOtp(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!pendingPhone || !/^\d{6}$/.test(code)) { setError("Enter the 6-digit verification code sent to your mobile."); return; } setLoading(true); setError(""); const { data, error: verificationError } = await createSupabaseBrowserClient().auth.verifyOtp({ phone: pendingPhone, token: code, type: "sms" }); if (verificationError || !data.user) { setError("That verification code is invalid or has expired. Request a new code and try again."); setLoading(false); return; } await redirectForUser(data.user.id); }
  return <div className="mt-8"><div className="grid grid-cols-2 rounded-xl border border-green-950/10 bg-[#f7faf5] p-1 text-sm font-bold"><button type="button" onClick={() => { setMode("email"); setError(""); setPendingPhone(null); }} className={`min-h-10 rounded-lg px-3 ${mode === "email" ? "bg-white text-leaf shadow-sm" : "text-slate-600"}`}>Email & password</button><button type="button" onClick={() => { setMode("phone"); setError(""); setPendingPhone(null); }} className={`min-h-10 rounded-lg px-3 ${mode === "phone" ? "bg-white text-leaf shadow-sm" : "text-slate-600"}`}>Mobile OTP</button></div>{mode === "email" ? <form onSubmit={submitPassword} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Email<input className={input} name="email" type="email" required /></label><label className="block text-sm font-semibold">Password<input className={input} name="password" type="password" required /></label>{error && <p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-leaf py-3 text-sm font-bold text-white">{loading ? "Signing in…" : "Log in"}</button></form> : !pendingPhone ? <form onSubmit={sendOtp} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Verified Indian mobile number<input className={input} value={phone} onChange={(e) => setPhone(e.target.value)} required /></label>{error && <p role="alert">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-leaf py-3 text-sm font-bold text-white">Send OTP</button></form> : <form onSubmit={verifyOtp} className="mt-5 space-y-4"><label className="block text-sm font-semibold">6-digit OTP<input className={input} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))} required /></label><button disabled={loading} className="w-full rounded-xl bg-leaf py-3 text-sm font-bold text-white">Verify and log in</button></form>}<p className="mt-5 text-center text-sm text-slate-600">New to FarmDirect? <Link className="font-bold text-leaf" href="/register">Create an account</Link></p></div>;
}

export function RegisterForm() {
  const router = useRouter(); const [role, setRole] = useState<RegistrationRole>("consumer"); const [phone, setPhone] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(null); const [locationMessage, setLocationMessage] = useState(""); const pickupRole = role === "farmer" || role === "fpo";
  function useCurrentLocation() { if (!navigator.geolocation) { setLocationMessage("We couldn't detect your location. Please try again."); return; } setLocationMessage("Getting your location..."); navigator.geolocation.getCurrentPosition((p) => { setLocation({ latitude: p.coords.latitude, longitude: p.coords.longitude }); setLocationMessage("✓ Pickup location captured"); }, (p) => setLocationMessage(p.code === p.PERMISSION_DENIED ? "Location permission was not granted. You can still complete registration." : "We couldn't detect your location. Please try again."), { enableHighAccuracy: true, timeout: 10000, maximumAge: 60000 }); }
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(""); const f = new FormData(e.currentTarget); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: f.get("email"), password: f.get("password"), fullName: f.get("fullName"), role, phone, city: f.get("city"), state: f.get("state"), farmName: f.get("farmName"), organizationName: f.get("organizationName"), latitude: location?.latitude ?? null, longitude: location?.longitude ?? null }) }); const result = await response.json() as { error?: string }; if (!response.ok) { setError(result.error ?? "Unable to create account."); setLoading(false); return; } const { error: loginError } = await createSupabaseBrowserClient().auth.signInWithPassword({ email: String(f.get("email")), password: String(f.get("password")) }); if (loginError) { router.push("/login"); return; } router.replace("/account/phone"); router.refresh(); }
  return <form onSubmit={submit} className="mt-7 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold sm:col-span-2">I am joining as<select value={role} onChange={(e) => setRole(e.target.value as RegistrationRole)} className={input}>{roles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="block text-sm font-semibold">Full name<input className={input} name="fullName" required minLength={2}/></label><label className="block text-sm font-semibold">Mobile number<input className={input} name="phone" value={phone} onChange={(e) => setPhone(e.target.value.replace(/\D/g, "").slice(0, 10))} inputMode="numeric" /></label>{role === "farmer" && <label className="block text-sm font-semibold sm:col-span-2">Farm name<input className={input} name="farmName" required /></label>}{role === "fpo" && <label className="block text-sm font-semibold sm:col-span-2">Organisation name<input className={input} name="organizationName" required /></label>}<label className="block text-sm font-semibold">City / village<input className={input} name="city" required /></label><label className="block text-sm font-semibold">State<input className={input} name="state" defaultValue="Maharashtra" required /></label>{pickupRole && <section className="rounded-xl border border-green-950/10 p-4 sm:col-span-2"><p className="font-semibold">Pickup location</p><button type="button" onClick={useCurrentLocation} className="mt-2 w-full rounded-xl border border-green-950/15 px-4 py-3 text-sm font-bold text-leaf">Use My Current Location</button>{locationMessage && <p className="mt-2 text-sm text-slate-600">{locationMessage}</p>}</section>}<label className="block text-sm font-semibold sm:col-span-2">Email<input className={input} name="email" type="email" required /></label><label className="block text-sm font-semibold sm:col-span-2">Password<input className={input} name="password" type="password" minLength={8} required /></label>{error && <p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700 sm:col-span-2">{error}</p>}<button disabled={loading} className="rounded-xl bg-leaf py-3 text-sm font-bold text-white disabled:opacity-60 sm:col-span-2">{loading ? "Creating account…" : "Create secure account"}</button><p className="text-center text-sm text-slate-600 sm:col-span-2">Already have an account? <Link className="font-bold text-leaf" href="/login">Log in</Link></p></form>;
}

export function LogoutButton({ className = "" }: { className?: string }) { const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function logout() { setLoading(true); setError(""); try { const { error: signOutError } = await createSupabaseBrowserClient().auth.signOut(); if (signOutError) { setError("Unable to sign out. Please try again."); return; } window.location.replace("/"); } catch { setError("Unable to sign out. Please try again."); } finally { setLoading(false); } } return <div className="relative"><button onClick={logout} disabled={loading} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold transition disabled:cursor-not-allowed disabled:opacity-60 ${className}`}><LogOut size={15}/>{loading ? "Signing out…" : "Log out"}</button>{error && <p role="alert" className="absolute right-0 top-full z-40 mt-2 w-52 rounded-lg bg-red-50 px-3 py-2 text-xs font-medium text-red-700 shadow-sm">{error}</p>}</div>; }
