"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Boxes, ClipboardList, Plus, Store } from "lucide-react";
import { DashboardActivity } from "../../../components/dashboard-activity";
import { createSupabaseBrowserClient } from "../../../lib/supabase/browser";

type Request = { id: string; product_name: string; required_quantity: number; unit: string; status: "requested" | "quoted" | "accepted" | "rejected" | "fulfilled" | "cancelled"; required_by: string | null; created_at: string };
const status = (value: Request["status"]) => ({ requested: "Open", quoted: "Quote received", accepted: "Accepted", rejected: "Not available", fulfilled: "Completed", cancelled: "Cancelled" }[value]);
const open = new Set<Request["status"]>(["requested", "quoted", "accepted"]);

export default function BulkDashboard() {
  const [requests, setRequests] = useState<Request[]>([]); const [message, setMessage] = useState("Loading your procurement requests…");
  useEffect(() => { createSupabaseBrowserClient().from("bulk_orders").select("id,product_name,required_quantity,unit,status,required_by,created_at").order("created_at", { ascending: false }).then(({ data, error }) => { if (error) setMessage(error.message); else { setRequests((data ?? []) as Request[]); setMessage(""); } }); }, []);
  const active = requests.filter((request) => open.has(request.status)); const total = requests.reduce((sum, request) => sum + Number(request.required_quantity), 0);
  return <main className="page-shell"><div className="app-container max-w-6xl">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">BULK BUYER PORTAL</p><h1 className="mt-2 text-3xl font-extrabold">Buy fresher. Plan better.</h1><p className="mt-2 text-slate-600">Create and track your direct procurement requests.</p></div><div className="flex w-full flex-wrap gap-2 sm:w-auto"><Link href="/bulk/orders" className="primary-button inline-flex flex-1 items-center justify-center gap-2 sm:flex-none"><Plus size={17} />Create Bulk Request</Link><Link href="/marketplace" className="soft-button inline-flex flex-1 items-center justify-center gap-2 sm:flex-none"><Store size={17} />Browse Marketplace</Link></div></div>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><article className="surface p-5"><p className="text-2xl font-extrabold text-leaf">{requests.length}</p><p className="mt-1 text-sm text-slate-600">Total requests</p></article><article className="surface p-5"><p className="text-2xl font-extrabold text-leaf">{active.length}</p><p className="mt-1 text-sm text-slate-600">Open requests</p></article><article className="surface p-5"><p className="text-2xl font-extrabold text-leaf">{total.toLocaleString("en-IN")}</p><p className="mt-1 text-sm text-slate-600">Total quantity requested</p></article></section>
    <section className="mt-7"><DashboardActivity /></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="surface p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">RECENT PROCUREMENT REQUESTS</p><h2 className="mt-1 text-xl font-bold">My requests</h2></div><Link href="/bulk/orders" className="soft-button">View My Requests</Link></div>{message ? <p className="mt-5 text-sm text-slate-600">{message}</p> : requests.length === 0 ? <div className="empty-state mt-5"><ClipboardList className="mx-auto text-leaf" /><p className="mt-3 font-semibold">No procurement requests yet.</p><Link href="/bulk/orders" className="primary-button mt-4 inline-flex">Create your first request</Link></div> : <div className="mt-5 space-y-3">{requests.slice(0, 5).map((request) => <Link key={request.id} href="/bulk/orders" className="block rounded-xl border border-green-900/10 p-4 hover:bg-green-50"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{request.product_name}</p><p className="mt-1 text-sm text-slate-600">{request.required_quantity} {request.unit}{request.required_by ? ` · Needed by ${new Date(`${request.required_by}T00:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}` : ""}</p></div><span className="status-badge">{status(request.status)}</span></div></Link>)}</div>}</div><aside className="rounded-2xl bg-ink p-6 text-white"><Boxes className="text-[#BCE19C]" /><h2 className="mt-5 text-xl font-bold">What needs attention?</h2><p className="mt-3 text-sm leading-6 text-slate-200">{active.length ? `${active.length} request${active.length === 1 ? " is" : "s are"} still open or progressing.` : requests.length ? "You have no active procurement requests right now." : "Create a request to start sourcing produce directly."}</p><Link href="/bulk/orders" className="mt-5 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-bold text-ink">{requests.length ? "Review requests" : "Create request"}</Link></aside></section>
  </div></main>;
}
