"use client";

import { FormEvent, useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "../../../lib/supabase/browser";

type BulkOrder = { id: string; product_name: string; required_quantity: number; unit: string; target_price_inr: number | null; status: string; delivery_address: string; required_by: string | null };
type Delivery = { bulk_order_id: string | null; status: string; requested_for: string | null };

export default function BulkOrders() {
  const [orders, setOrders] = useState<BulkOrder[]>([]); const [deliveries, setDeliveries] = useState<Record<string, Delivery>>({}); const [message, setMessage] = useState("");
  async function load() { const supabase = createSupabaseBrowserClient(); const result = await supabase.from("bulk_orders").select("id,product_name,required_quantity,unit,target_price_inr,status,delivery_address,required_by").order("created_at", { ascending: false }); if (result.error) { setMessage(result.error.message); return; } const next = (result.data ?? []) as BulkOrder[]; setOrders(next); if (!next.length) { setDeliveries({}); return; } const deliveryResult = await supabase.from("delivery_requests").select("bulk_order_id,status,requested_for").in("bulk_order_id", next.map((order) => order.id)); if (deliveryResult.error) { setMessage(deliveryResult.error.message); return; } setDeliveries(Object.fromEntries((deliveryResult.data ?? []).filter((delivery) => delivery.bulk_order_id).map((delivery) => [delivery.bulk_order_id as string, delivery as Delivery]))); }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const supabase = createSupabaseBrowserClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setMessage("Please log in as a Bulk Buyer."); return; } const result = await supabase.from("bulk_orders").insert({ buyer_id: user.id, product_name: form.get("product_name"), required_quantity: Number(form.get("quantity")), unit: form.get("unit"), target_price_inr: form.get("target_price") ? Number(form.get("target_price")) : null, delivery_address: form.get("address"), required_by: form.get("date") || null, notes: form.get("notes") || null }).select().single(); setMessage(result.error ? result.error.message : `Request ${result.data.id.slice(0, 8)} created.`); if (!result.error) { event.currentTarget.reset(); await load(); } }
  return <main className="page-shell p-8"><h1 className="text-3xl font-extrabold">Bulk requests</h1><form onSubmit={submit} className="mt-6 grid gap-3 rounded-xl bg-white p-5 sm:grid-cols-2"><input name="product_name" required placeholder="Crop or product" className="border p-2"/><input name="quantity" required type="number" min="1" placeholder="Quantity" className="border p-2"/><select name="unit" className="border p-2"><option>kg</option><option>quintal</option></select><input name="target_price" type="number" min="1" placeholder="Target ₹ / unit" className="border p-2"/><input name="address" required placeholder="Delivery location" className="border p-2"/><input name="date" type="date" className="border p-2"/><textarea name="notes" placeholder="Notes" className="border p-2 sm:col-span-2"/><button className="rounded-lg bg-leaf p-3 font-bold text-white sm:col-span-2">Submit request</button></form>{message && <p className="mt-4">{message}</p>}<div className="mt-6 space-y-3">{orders.length === 0 && <p className="rounded-xl bg-white p-4">No bulk requests yet.</p>}{orders.map((order) => { const delivery = deliveries[order.id]; return <article key={order.id} className="rounded-xl bg-white p-4"><b>{order.product_name}</b><p>{order.required_quantity} {order.unit} · {order.status} · {order.target_price_inr ? `₹${order.target_price_inr}` : "Price open"}</p><p className="text-sm">{order.delivery_address} {order.required_by && `· Required ${order.required_by}`}</p>{delivery ? <p className="mt-2 text-sm text-leaf">Delivery: {delivery.status}{delivery.requested_for ? ` · requested ${delivery.requested_for}` : ""}</p> : <p className="mt-2 text-sm text-slate-500">Delivery has not been scheduled.</p>}</article>; })}</div></main>;
}
