"use client";

import { FormEvent, useEffect, useMemo, useState, type Dispatch, type SetStateAction } from "react";
import { createSupabaseBrowserClient } from "../../../../lib/supabase/browser";

type Item = { seller_id: string; product_name: string; quantity: number; unit: string };
type Delivery = { id: string; order_id: string | null; pickup_address: string; pickup_latitude: number; pickup_longitude: number; dropoff_address: string; dropoff_latitude: number; dropoff_longitude: number; load_quantity: number; status: string };
type Order = { id: string; status: string; delivery_address: string; delivery_latitude: number | null; delivery_longitude: number | null; order_items: Item[]; delivery_requests: { id: string } | { id: string }[] | null };
type Location = { name: string; address: string | null; latitude: number | null; longitude: number | null };
type Values = { pickup: string; plat: string; plng: string; drop: string; dlat: string; dlng: string; load: string };
const blank: Values = { pickup: "", plat: "", plng: "", drop: "", dlat: "", dlng: "", load: "" };
const db = () => createSupabaseBrowserClient();
const hasDelivery = (value: Order["delivery_requests"]) => Array.isArray(value) ? value.length > 0 : Boolean(value);
const valuesFor = (delivery: Delivery): Values => ({ pickup: delivery.pickup_address, plat: String(delivery.pickup_latitude), plng: String(delivery.pickup_longitude), drop: delivery.dropoff_address, dlat: String(delivery.dropoff_latitude), dlng: String(delivery.dropoff_longitude), load: String(delivery.load_quantity) });

export default function ManageLogistics() {
  const [deliveries, setDeliveries] = useState<Delivery[]>([]), [orders, setOrders] = useState<Order[]>([]), [locations, setLocations] = useState<Record<string, Location>>({}), [selectedOrderId, setSelectedOrderId] = useState(""), [request, setRequest] = useState<Values>(blank), [editing, setEditing] = useState<Delivery | null>(null), [edit, setEdit] = useState<Values>(blank), [routed, setRouted] = useState<Set<string>>(new Set()), [message, setMessage] = useState("");
  const [routes, setRoutes] = useState<Array<{ id: string }>>([]);
  const selected = useMemo(() => orders.find((order) => order.id === selectedOrderId), [orders, selectedOrderId]);
  async function load() {
    const s = db(); const [dr, or, sr] = await Promise.all([s.from("delivery_requests").select("id,order_id,pickup_address,pickup_latitude,pickup_longitude,dropoff_address,dropoff_latitude,dropoff_longitude,load_quantity,status").order("created_at", { ascending: false }), s.from("orders").select("id,status,delivery_address,delivery_latitude,delivery_longitude,order_items(seller_id,product_name,quantity,unit),delivery_requests(id)").in("status", ["placed", "confirmed", "packed", "out_for_delivery"]).order("created_at", { ascending: false }), s.from("route_stops").select("delivery_request_id")]);
    const routeResult = await s.from("delivery_routes").select("id").order("created_at", { ascending: false });
    setRoutes(routeResult.data ?? []);
    if (dr.error || or.error || sr.error) { setMessage(dr.error?.message ?? or.error?.message ?? sr.error?.message ?? "Unable to load logistics data."); return; }
    const nextDeliveries = (dr.data ?? []) as Delivery[]; setDeliveries(nextDeliveries); setRouted(new Set((sr.data ?? []).flatMap((stop) => stop.delivery_request_id ? [stop.delivery_request_id] : [])));
    const eligible = ((or.data ?? []) as Order[]).filter((order) => order.order_items.length && !hasDelivery(order.delivery_requests)); setOrders(eligible);
    const ids = [...new Set(eligible.flatMap((order) => order.order_items.map((item) => item.seller_id)))]; if (!ids.length) return;
    const [farmers, fpos] = await Promise.all([s.from("farmer_profiles").select("user_id,farm_name,address,latitude,longitude").in("user_id", ids), s.from("fpo_profiles").select("user_id,organization_name,address,latitude,longitude").in("user_id", ids)]);
    const next: Record<string, Location> = {}; farmers.data?.forEach((x) => next[x.user_id] = { name: x.farm_name, address: x.address, latitude: x.latitude, longitude: x.longitude }); fpos.data?.forEach((x) => next[x.user_id] = { name: x.organization_name, address: x.address, latitude: x.latitude, longitude: x.longitude }); setLocations(next);
  }
  useEffect(() => { void load(); }, []);
  const change = (setter: Dispatch<SetStateAction<Values>>, key: keyof Values, value: string) => setter((current) => ({ ...current, [key]: value }));
  function choose(id: string) { setSelectedOrderId(id); const order = orders.find((x) => x.id === id); if (!order) return setRequest(blank); const sellerIds = [...new Set(order.order_items.map((x) => x.seller_id))], seller = sellerIds.length === 1 ? locations[sellerIds[0]] : undefined, kg = order.order_items.every((x) => x.unit === "kg"); setRequest({ pickup: seller?.address ?? "", plat: seller?.latitude?.toString() ?? "", plng: seller?.longitude?.toString() ?? "", drop: order.delivery_address, dlat: order.delivery_latitude?.toString() ?? "", dlng: order.delivery_longitude?.toString() ?? "", load: kg ? String(order.order_items.reduce((sum, x) => sum + Number(x.quantity), 0)) : "" }); }
  async function create(event: FormEvent) { event.preventDefault(); if (!selectedOrderId) return setMessage("Select an eligible order first."); const { data: { user } } = await db().auth.getUser(); const r = await db().from("delivery_requests").insert({ requester_id: user?.id, order_id: selectedOrderId, pickup_address: request.pickup, pickup_latitude: Number(request.plat), pickup_longitude: Number(request.plng), dropoff_address: request.drop, dropoff_latitude: Number(request.dlat), dropoff_longitude: Number(request.dlng), load_quantity: Number(request.load), status: "requested" }); setMessage(r.error?.message ?? "Delivery request created."); if (!r.error) { setSelectedOrderId(""); setRequest(blank); await load(); } }
  async function saveEdit(event: FormEvent) { event.preventDefault(); if (!editing) return; const r = await fetch(`/api/admin/logistics/delivery-requests/${editing.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pickup_address: edit.pickup, pickup_latitude: Number(edit.plat), pickup_longitude: Number(edit.plng), dropoff_address: edit.drop, dropoff_latitude: Number(edit.dlat), dropoff_longitude: Number(edit.dlng), load_quantity: Number(edit.load) }) }); const body = await r.json(); setMessage(r.ok ? "Delivery request updated." : body.error ?? "Unable to update delivery request."); if (r.ok) { setEditing(null); await load(); } }
  async function addStop(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await db().from("route_stops").insert({ route_id: form.get("route"), delivery_request_id: form.get("delivery") || null, stop_order: Number(form.get("sequence")), stop_type: form.get("type"), address: form.get("address"), latitude: Number(form.get("lat")), longitude: Number(form.get("lng")), load_change_kg: Number(form.get("load") || 0), status: "scheduled" }); setMessage(result.error?.message ?? "Stop added."); if (!result.error) await load(); }
  const fields = (value: Values, setter: Dispatch<SetStateAction<Values>>) => <>{[["pickup", "Pickup address", "text"], ["drop", "Destination", "text"], ["plat", "Pickup latitude", "number"], ["plng", "Pickup longitude", "number"], ["dlat", "Destination latitude", "number"], ["dlng", "Destination longitude", "number"], ["load", "Load kg", "number"]].map(([key, label, type]) => <label key={key} className="text-sm font-semibold">{label}<input value={value[key as keyof Values]} onChange={(e) => change(setter, key as keyof Values, e.target.value)} required type={type} step="any" className="mt-1 w-full rounded border p-2" /></label>)}</>;
  return <main className="page-shell p-6"><div className="mx-auto max-w-6xl"><h1 className="text-2xl font-extrabold">Manual logistics operations</h1>{message && <p className="mt-3 rounded bg-green-50 p-3 text-sm" role="status">{message}</p>}
    <form onSubmit={create} className="mt-5 grid gap-3 rounded-xl bg-white p-5 shadow-sm md:grid-cols-2"><div className="md:col-span-2"><h2 className="font-bold">Create delivery request</h2><p className="mt-1 text-sm text-slate-600">Select an eligible order. Coordinates are required for route optimization and remain manual when no authoritative value exists.</p></div><label className="md:col-span-2 text-sm font-semibold">Select order<select value={selectedOrderId} onChange={(e) => choose(e.target.value)} required className="mt-1 w-full rounded border p-2"><option value="">Choose an eligible order</option>{orders.map((o) => <option key={o.id} value={o.id}>Order #{o.id.slice(0, 8)} · {o.order_items.map((x) => `${x.product_name} (${x.quantity} ${x.unit})`).join(", ")}</option>)}</select></label>{selected && <p className="rounded-lg bg-[#edf4e4] p-3 text-sm md:col-span-2">Order #{selected.id.slice(0, 8)} · {selected.order_items.map((x) => `${x.product_name} ${x.quantity} ${x.unit}`).join(", ")}<br />Delivery: {selected.delivery_address}</p>}{fields(request, setRequest)}<button className="rounded bg-leaf p-2 text-white md:col-span-2">Create request</button></form>
    <section className="mt-7"><h2 className="text-xl font-bold">Delivery requests</h2><p className="mt-1 text-sm text-slate-600">Inspect coordinates before route optimization. Routed or non-eligible requests are locked to protect persisted routes.</p><div className="mt-3 space-y-3">{deliveries.map((d) => { const locked = routed.has(d.id) || !["requested", "scheduled"].includes(d.status); return <article key={d.id} className="rounded-xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><b>Request #{d.id.slice(0, 8)} · Order {d.order_id?.slice(0, 8) ?? "—"}</b><p className="mt-1 text-sm capitalize">{d.status} · {d.load_quantity} kg</p></div>{locked ? <span className="text-sm text-slate-500">Editing unavailable</span> : <button onClick={() => { setEditing(d); setEdit(valuesFor(d)); }} className="soft-button">Edit</button>}</div><div className="mt-4 grid gap-3 text-sm md:grid-cols-2"><p><b>Pickup</b><br />{d.pickup_address}<br />{d.pickup_latitude}, {d.pickup_longitude}</p><p><b>Destination</b><br />{d.dropoff_address}<br />{d.dropoff_latitude}, {d.dropoff_longitude}</p></div>{locked && <p className="mt-3 text-sm text-slate-500">This request is already routed or is no longer in a safe editable status.</p>}{editing?.id === d.id && <form onSubmit={saveEdit} className="mt-5 grid gap-3 border-t border-green-950/10 pt-4 md:grid-cols-2">{fields(edit, setEdit)}<div className="flex gap-3 md:col-span-2"><button className="rounded bg-leaf px-4 py-2 text-sm font-bold text-white">Save corrections</button><button type="button" onClick={() => setEditing(null)} className="soft-button">Cancel</button></div></form>}</article>; })}</div></section>
    <form onSubmit={addStop} className="mt-7 grid gap-2 rounded-xl bg-white p-5 shadow-sm md:grid-cols-2"><div className="md:col-span-2"><h2 className="font-bold">Manual route stops</h2><p className="mt-1 text-sm text-slate-600">Use for manually managed routes only; delivery requests remain available for the route optimizer.</p></div><select name="route" required className="border p-2"><option value="">Select route</option>{routes.map((route) => <option key={route.id} value={route.id}>{route.id.slice(0, 8)}</option>)}</select><select name="delivery" className="border p-2"><option value="">No delivery link</option>{deliveries.map((delivery) => <option key={delivery.id} value={delivery.id}>{delivery.id.slice(0, 8)}</option>)}</select><input name="sequence" required min="1" type="number" placeholder="Sequence" className="border p-2" /><select name="type" className="border p-2"><option>pickup</option><option>delivery</option></select><input name="address" required placeholder="Address" className="border p-2" /><input name="lat" required type="number" step="any" placeholder="Latitude" className="border p-2" /><input name="lng" required type="number" step="any" placeholder="Longitude" className="border p-2" /><input name="load" type="number" step="any" placeholder="Load change kg" className="border p-2" /><button className="rounded bg-leaf p-2 text-white md:col-span-2">Add stop</button></form>
  </div></main>;
}
